# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Z_AigM243BtiDWlHvniZV2R-s7sHoEcg
"""

sentence = input("")
words = sentence.split()
result = {}
for word in words:
    result[word] = sentence.count(word)
result

a = int(input(""))
b = int(input(""))
k = input("")
result = {
    "+": {"operator": "+", "result": a + b},
    "-": {"operator": "-", "result": a - b},
    "/": {"operator": "/", "result": a / b},
    "*": {"operator": "*", "result": a * b},
    "**": {"operator": "**", "result": a ** b},
    "%": {"operator": "%", "result": a % b},
}
product = result.get(k)
product